// put your action types here
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const ADD_NEW_TODO = 'ADD_NEW_TODO'
export const TOGGLE_DISPLAY_COMPLETEDS = 'TOGGLE_DISPLAY_COMPLETEDS'
export const TOGGLE_COMPLETION = 'TOGGLE_COMPLETION'
